// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute, Params } from "@angular/router";
import swal from 'sweetalert';
import { ArticleService } from "../../services/article.service";
import { Article } from "../../models/article";

import { Global } from "../../services/global"; 

@Component({
  selector: 'app-article',
  templateUrl: './article.component.html',
  styleUrls: ['./article.component.css'],
  providers: [ArticleService]
})
export class ArticleComponent implements OnInit {
  public article: Article;
  public articleId : string;
  public url: string;

  constructor(
    private _route: ActivatedRoute,
    private _router: Router,
    public _articleService: ArticleService
  ) {
    this.url = Global.url
   }

  ngOnInit(): void {

    this._route.params.subscribe((params: Params)=>{
      this.articleId = params.id
    });

    this._articleService.getArticle(this.articleId).subscribe(
      response=>{
        if(response.article){
          this.article = response.article
        } else{
          this._router.navigate(['/home']);
        }
        
      },
      error => {
        console.log(error);
        this._router.navigate(['/home']);
      }
    )
  }

  delete(id){

    swal({
      title: "¿Estás seguro de eliminar tu artículo?",
      text: "Una vez eliminado, no vas a poder recuperar tu artículo!",
      icon: "warning",
      buttons: [true, true],
      dangerMode: true,
    })
    .then((willDelete) => {
      if (willDelete) {
        this._articleService.delete(id).subscribe(
          response=>{
            swal("Tu artículo ha sido eliminado!", {
              icon: "success",
            });
            this._router.navigate(['/blog']);
          },
          error=>{
            console.log(error);
            this._router.navigate(['/blog']);
          }
        )
        
      } else {
        swal("Tu artículo no se ha eliminado!");
      }
    });


    
  }

}

<div class="center">
  <section id="content">
    <article class="article-item article-detail" *ngIf="article">
        <div class="image-wrap">
            <img
        src="{{ url + 'get-image/' + article.image }}"
        alt="{{ article.title }}"
        *ngIf="article.image"
      />
      <img
        src="assets/images/default.png"
        alt="{{ article.title }}"
        *ngIf="!article.image"
      />
        </div>

        <h1 class="subheader">{{article.title}}</h1>
        <span class="date"> {{ article.date | amLocale: "es" | amTimeAgo }} </span>
        <p>
           {{article.content}}
        </p>
        <div class="buttons">
            <a [routerLink]="['/blog/editar', article._id]" class="btn btn-warning">Editar</a>
            <a (click)="delete(article._id)" class="btn btn-danger">Borrar</a>
        </div>
        <div class="clearfix"></div>
    </article>
  </section>
  <app-sidebar></app-sidebar>
</div>

// AprendiendoVue/src/components/Article.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content">
        <article class="article-item article-detail" v-if="article">
          <div class="image-wrap">
            <img
              :src="url + 'get-image/' + article.image"
              :alt="article.title"
              v-if="article.image"
            />
            <img
              src="../assets/images/default.png"
              :alt="article.title"
              v-else
            />
          </div>

          <h1 class="subheader">{{ article.title }}</h1>
          <span class="date"> {{ article.date | moment("from", "now") }}</span>
          <p>{{ article.content }}</p>
          <div class="clearfix"></div>
          <router-link :to="'/editar/' + article._id" class="btn btn-warning"
            >Editar</router-link
          >
          <a @click="deletedArticle(article._id)" class="btn btn-danger"
            >Eliminar</a
          >
        </article>
      </section>
      <Sidebar />
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import Sidebar from "./Sidebar";
import swal from "sweetalert";
import axios from "axios";
import Global from "../Global";

export default {
  name: "Article",
  components: {
    Sidebar,
  },
  data() {
    return {
      url: Global.url,
      article: null,
    };
  },
  mounted() {
    var articleId = this.$route.params.id;
    this.getArticle(articleId);
  },
  methods: {
    getArticle(articleId) {
      axios.get(this.url + "article/" + articleId).then((res) => {
        if (res.data.status === "success") {
          this.article = res.data.article;
        }
      });
    },
    deletedArticle(articleId) {
      swal({
        title: "Estás seguro de borrarlo?",
        text: "Una vez borrado no se podrá recuperar!",
        icon: "warning",
        buttons: true,
        dangerMode: true,
      }).then((willDelete) => {
        if (willDelete) {
          axios.delete(this.url + "article/" + articleId).then(() => {
            swal(
              "Artículo borrado",
              "El artículo se ha borrado con éxito",
              "success"
            );
            this.$router.push("/blog");
          });
        } else {
          swal("Tu archivo está a salvo");
        }
      });
    },
  },
};
</script>
