// AprendiendoAngular/src/app/components/formulario/formulario.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-formulario',
  templateUrl: './formulario.component.html',
  styleUrls: ['./formulario.component.css']
})
export class FormularioComponent implements OnInit {

  public user: any;
  public campo: string;
  constructor() { 
    this.user = {
      nombre: '',
      apellidos: '',
      bio: '',
      genero: ''
    };
  }

  ngOnInit(): void {
  }


  onSubmit(){
    if(!this.user.nombre || !this.user.apellidos || !this.user.bio || !this.user.genero){
      return alert("Es necesario rellenar todos los campos")
    }else{
      
    console.log(this.user);
    alert("Formulario enviado!!");
    }
  }

  hasDadoClick(){
    alert("Has dado click")
  }
  hasSalido(){
    alert("Has salido del campo")
  }

}

<app-slider [nombre]="'Formulario'" [size]="'small'"></app-slider>

<div class="center">
  <section id="content">
    <h1 class="subheader">Formulario</h1>

   <!--  <div id="datos-al-vuelo" *ngIf="user.nombre">
      <h2 class="subheader">
        Datos al vuelo
      </h2>
      <hr>
      <ul>
        <li>{{user.nombre}}</li>
        <li>{{user.apellidos}}</li>
        <li>{{user.bio}}</li>
        <li>{{user.genero}}</li>
      </ul>
    </div> -->

    <form class="mid-form" #userForm="ngForm"  (ngSubmit)="onSubmit()">
      <div class="form-group">
        <label for="nombre">Nombre</label>
        <input type="text" name="nombre" #nombre="ngModel" [(ngModel)]="user.nombre" required pattern="[a-zA-Z]+"/>

        <small *ngIf="!nombre.valid && nombre.touched">El nombre no es válido</small>
      </div>

      <div class="form-group">
        <label for="apellidos">Apellidos</label>
        <input type="text" name="apellidos" #apellidos="ngModel" [(ngModel)]="user.apellidos" required/>
        <small *ngIf="!apellidos.valid && apellidos.touched">Los apellidos no son válidos</small>
      </div>

      <div class="form-group">
        <label for="bio">Biografia</label>
        <textarea name="bio" #bio="ngModel" [(ngModel)]="user.bio" required></textarea>
        <small *ngIf="!bio.valid && bio.touched">El campo biografía no es válido</small>
      </div>

      <div class="form-group radibuttons">
        <input type="radio" name="genero" #genero="ngModel" value="hombre" [(ngModel)]="user.genero" required/> Hombre
        <input type="radio" name="genero" #genero="ngModel" value="mujer" [(ngModel)]="user.genero"/> Mujer
        <input type="radio" name="genero" #genero="ngModel" value="otro" [(ngModel)]="user.genero"/> Otro
        <small *ngIf="!genero.valid && genero.touched">El campo biografía no es válido</small>
      </div>

      <div class="clearfix"></div>

      <input type="submit" value="Enviar" class="btn btn-success" [disabled]="userForm.invalid"/>
    </form>
    <h2 class="subheader">Eventos</h2>
    <button (click)="hasDadoClick()">Dar click</button>
    <input type="text" [(ngModel)]="campo" (keyup)="hasSalido()">
    {{campo}}
  </section>
  <app-sidebar></app-sidebar>
</div>

// AprendiendoVue/src/components/Formulario.vue
<template>
  <div class="general">
    <div class="center">
      <section id="content" @submit.prevent="mostrarUsuario()">
        <h2 class="subheader">Formulario</h2>
        <form class="mid-form">
          <div class="form-group">
            <label for="nombre">Nombre</label>
            <input type="text" name="nombre" v-model="user.nombre" />
            <div v-if="submitted && !$v.user.nombre.required">Este campo es requerido</div>
            <div v-if="submitted && !$v.user.nombre.minLength">Este campo debe tener más caracteres</div>
          </div>
          <div class="form-group">
            <label for="apellidos">Apellidos</label>
            <input type="text" name="apellidos" v-model="user.apellidos" />
            <div v-if="submitted && !$v.user.apellidos.required">
              Este campo es requerido
            </div>
          </div>

          <div class="form-group">
            <label for="bio">Biografia</label>
            <textarea name="bio" v-model="user.bio"></textarea>
            <div v-if="submitted && !$v.user.bio.required">Este campo es requerido</div>
          </div>

          <div class="form-group radibuttons">
            <input
              type="radio"
              name="genero"
              value="hombre"
              checked
              v-model="user.genero"
            />
            Hombre
            <input
              type="radio"
              name="genero"
              value="mujer"
              v-model="user.genero"
            />
            Mujer
            <input
              type="radio"
              name="genero"
              value="otro"
              v-model="user.genero"
            />
            Otro
          </div>
          <div class="clearfix"></div>

          <input type="submit" value="Enviar" class="btn btn-success" />
        </form>
        <div class="datos" v-if="user.nombre && user.apellidos">
          <h3>{{ user.nombre + " " + user.apellidos }}</h3>
        </div>
      </section>
      <Sidebar />
      <div class="clearfix"></div>
    </div>
  </div>
</template>

<script>
import { required, minLength } from "vuelidate/lib/validators";

import Sidebar from "./Sidebar.vue";
export default {
  name: "Formulario",
  components: {
    Sidebar,
  },
  validations: {
    user: {
      nombre: {
        required,
        minLength: minLength(2),
      },
      apellidos: {
        required,
        minLength: minLength(2),
      },
      bio: {
        required,
        minLength: minLength(10),
      },
    },
  },
  methods: {
    mostrarUsuario() {
      console.log(this.user);
      this.submitted = true;

      this.$v.$touch();
      if (this.$v.$invalid) {
        return false;
      }
      alert("Validación pasada");
    },
  },
  data() {
    return {
      submitted: false,
      user: {
        nombre: "",
        apellidos: "",
        bio: "",
        genero: "",
      },
    };
  },
};
</script>
